name = "Havoc Retfart S2"
author = "awesomebossdj7"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b0797833889f0fb3345505b3a9f01ff980540f02ffedc77a8e514914e847903"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["neoforge"]
