name = "Havoc Retfart"
author = "awesomebossdj7"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "512c31b02b62b5ae672bf631a6b7d4df7240a070cc5315138679b74e6b326821"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["neoforge"]
