name = "Havoc Retfart"
author = "awesomebossdj7"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c39795e8e6e1a3c55dafa41ba1f50c2326a513b44dd695a09fb39601fa7d3d5"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["neoforge"]
