name = "Havoc Retfart"
author = "awesomebossdj7"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f363b3f924bb3ff0d9ce61e97422d17bcdd68e433dfc662379bb827dd705e83a"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["neoforge"]
