name = "Havoc Retfart S2"
author = "awesomebossdj7"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb21e8e833bcdb2d34334893178733a4a214b4738bd5865c388b4cc9e815a425"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["neoforge"]
