name = "Havoc Retfart"
author = "awesomebossdj7"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "739e807a5f50bb3876fa5016164d9b1eabe938ecf0852434d47d97aaf7e41494"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["neoforge"]
