name = "Havoc Retfart"
author = "awesomebossdj7"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da7e6e4a623240a05af946ff39bca19d80ca96b37fc55406bad8c08afb1ac76d"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["neoforge"]
