name = "Havoc Retfart"
author = "awesomebossdj7"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05ff5cc41c940a266288d09ea4b5f0b30fae6b4609645d74d2dd0db6cc6376e0"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["neoforge"]
