name = "Havoc Retfart"
author = "awesomebossdj7"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03f6dc21804dd157e39e7f3f1d49eb9c8668685a3e95ac157328413a96e09c83"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["neoforge"]
